"""Root STAC catalog generator.

Walks ``stac_output_dir`` to find every ``collection.json`` produced by the
per-source generators, groups them by ``group_id`` (and optionally ``event_id``)
and emits a top-level ``catalog.json`` that links the resulting hierarchy.

Root metadata (id/title/description) is taken from the optional project
settings; callers may also pass an explicit ``project`` dict to override.
"""

from __future__ import annotations

import shutil
from collections import defaultdict
from pathlib import Path
from typing import Optional

import pystac
from loguru import logger

from src.core.event_collection import build_event_collection


DEFAULT_PROJECT = {
    "id": "stac-root-catalog",
    "title": "STAC Catalog",
    "description": "STAC catalog generated by stac-builder.",
}


def _resolve_project(project: Optional[dict]) -> dict:
    if project:
        return {**DEFAULT_PROJECT, **project}
    try:
        from src.settings import get_settings  # lazy
        s = get_settings()
        if s and s.project:
            return {
                "id": s.project.id,
                "title": s.project.title,
                "description": s.project.description,
            }
    except Exception:
        pass
    return dict(DEFAULT_PROJECT)


def update_root_catalog(
    stac_output_dir: Path,
    project: Optional[dict] = None,
) -> None:
    """Generate a root STAC Catalog linking to all collections under ``stac_output_dir``."""
    proj = _resolve_project(project)
    root_catalog_path = stac_output_dir / "catalog.json"

    root = pystac.Catalog(
        id=proj["id"],
        title=proj["title"],
        description=proj["description"],
    )

    collection_paths = list(stac_output_dir.rglob("collection.json"))

    groups: dict[str, dict] = defaultdict(
        lambda: {"event_map": defaultdict(list), "plain": []}
    )

    loaded_cols: list[pystac.Collection] = []
    for col_path in collection_paths:
        try:
            col = pystac.Collection.from_file(str(col_path))
            loaded_cols.append(col)
        except Exception as e:
            logger.warning(f"Failed to load collection {col_path}: {e}")

    aggregated_ids = {
        c.id for c in loaded_cols if c.extra_fields.get("aggregation_type") == "event_collection"
    }

    for col in loaded_cols:
        if col.extra_fields.get("aggregation_type") == "event_collection":
            continue
        if col.id in aggregated_ids:
            continue

        group_name = col.extra_fields.get("group_id", "ungrouped")
        event_id = col.extra_fields.get("event_id")
        if event_id:
            groups[group_name]["event_map"][event_id].append(col)
        else:
            groups[group_name]["plain"].append(col)

    for group_name, payload in groups.items():
        all_cols: list[pystac.Collection] = []
        for _, lst in payload["event_map"].items():
            all_cols.extend(lst)
        all_cols.extend(payload["plain"])
        if not all_cols:
            continue

        event_col_ids = {c.id for cols in payload["event_map"].values() for c in cols}
        plain_cols = [c for c in payload["plain"] if c.id not in event_col_ids]

        group_dir = stac_output_dir / group_name
        group_dir.mkdir(exist_ok=True)

        first_col = all_cols[0]
        group_keywords = first_col.extra_fields.get("group_keywords", [])
        group_title = first_col.extra_fields.get(
            "group_title", group_name.replace("_", " ").title()
        )
        group_desc = first_col.extra_fields.get(
            "group_description", f"Group Catalog for {group_name}"
        )

        group_cat = pystac.Catalog(
            id=group_name,
            description=group_desc,
            title=group_title,
        )
        if group_keywords:
            group_cat.extra_fields["keywords"] = group_keywords
        group_cat.set_self_href(str(group_dir / "catalog.json"))

        for event_id, cols in payload["event_map"].items():
            by_id: dict[str, pystac.Collection] = {}
            for c in cols:
                cur = by_id.get(c.id)
                if cur is None or len(Path(c.self_href).parts) < len(Path(cur.self_href).parts):
                    by_id[c.id] = c
            cols = list(by_id.values())

            event_dir = group_dir / event_id
            event_dir.mkdir(exist_ok=True)

            first_event_col = cols[0]
            event_title = first_event_col.extra_fields.get(
                "event_title", event_id.replace("_", " ").title()
            )
            event_desc = first_event_col.extra_fields.get(
                "event_description", f"Event catalog for {event_id}"
            )

            for col in cols:
                old_col_dir = Path(col.self_href).parent
                new_col_dir = event_dir / old_col_dir.name
                try:
                    if old_col_dir.resolve() != new_col_dir.resolve():
                        if new_col_dir.exists():
                            logger.info(f"Removing stale collection directory: {new_col_dir}")
                            shutil.rmtree(new_col_dir)
                        shutil.move(str(old_col_dir), str(new_col_dir))
                        logger.info(f"Moved {old_col_dir.name} to {group_name}/{event_id}/")
                    col.set_self_href(str(new_col_dir / "collection.json"))
                except Exception as e:
                    logger.error(f"Failed to move {old_col_dir} to {new_col_dir}: {e}")

            event_collection = build_event_collection(
                stac_root=stac_output_dir,
                event_dir=event_dir,
                event_id=event_id,
                event_title=event_title,
                event_desc=event_desc,
                cols=cols,
            )
            group_cat.add_child(event_collection)

        for col in plain_cols:
            old_col_dir = Path(col.self_href).parent
            new_col_dir = group_dir / old_col_dir.name
            try:
                if old_col_dir.resolve() != new_col_dir.resolve():
                    if new_col_dir.exists():
                        logger.info(f"Removing stale collection directory: {new_col_dir}")
                        shutil.rmtree(new_col_dir)
                    shutil.move(str(old_col_dir), str(new_col_dir))
                    logger.info(f"Moved {old_col_dir.name} to {group_name}/")
                col.set_self_href(str(new_col_dir / "collection.json"))
            except Exception as e:
                logger.error(f"Failed to move {old_col_dir} to {new_col_dir}: {e}")
            group_cat.add_child(col)

        root.add_child(group_cat)

    root.set_self_href(str(root_catalog_path))
    root.save(catalog_type=pystac.CatalogType.SELF_CONTAINED)

    logger.info(f"Root Catalog written to {root_catalog_path}")
